# Generated by Django 3.0.8 on 2020-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Your Bio is empty', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default='default_cover.jpg', upload_to='profile_cover_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
